---
version: '3'
tasks:
  default: {cmds: [{task: lint}, {task: test}, {task: build}], silent: true}
  pre-push: {cmds: [{task: lint}, {task: test}], silent: true}
  lint: {cmds: ['golint --fix', 'golangci-lint run'], silent: true}
  test: {cmds: ['gotestsum --format standard-quiet'], silent: true}
  build: {cmds: [gobuild], silent: true}
  update: {cmds: [goupdate], silent: true}
  update-library: {cmds: ['goupdate --exclusive funtimecoding'], silent: true}
  dependency:
    # Alpine package: libvirt-dev
    cmds:
    - |
      [ $(uname) = 'Darwin' ] && brew install qemu libvirt || true
    silent: true
  tool:
    cmds:
    - |
      go install gotest.tools/gotestsum@latest
      go install github.com/funtimecoding/go-library/cmd/golint@latest
      go install github.com/funtimecoding/go-library/cmd/gobuild@latest
      curl -sSfL \
        https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh \
        | sh -s -- -b $(go env GOPATH)/bin
    silent: true
  install: {cmds: ['gobuild --copy-to-bin'], silent: true}
  build-github: {cmds: ['go build -v ./...'], silent: true}
  test-github: {cmds: ['go test -v ./...'], silent: true}
