---
name: Build
on: {push: {branches: [main]}, pull_request: {branches: [main]}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - {name: Repository, uses: actions/checkout@v4}
    - {name: Go, uses: actions/setup-go@v5, with: {go-version-file: go.mod}}
    - name: libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y libvirt-dev
    - {name: Dependency, run: 'go mod tidy'}
    - name: Task
      # https://github.com/go-task/task/releases
      run: |
        wget --quiet https://github.com/go-task/task/releases/download/v3.45.4/task_linux_amd64.deb
        sudo dpkg -i task_linux_amd64.deb
    - {name: Build, run: 'task build-github'}
    - {name: Test, run: 'task test-github'}
